name: flutter_sticky_header
description: Flutter implementation of sticky headers as a sliver. Use it in a CustomScrollView.
version: 0.6.5
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  value_layout_builder:
    path: value_layout_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  sliver_tools: ^0.2.7

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.24.0-10.2.pre'
